### ISSUE TITLE
0.6.0: sphinx 4.x failds on render `sphinx-panels` module documentation

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-panels#74]
### Describe the problem

Looks like sphinx 4.x failds on render `sphinx-panels` module documentation.
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... ExecutableBooksProject.1 { } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 346, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-11es7su9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@ss-desktop SPECS]$ cat /tmp/sphinx-err-11es7su9.log
# Sphinx version: 4.3.1
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   writing...
#   ExecutableBooksProject.1 {
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.3.1) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx_panels (0.6.0) from /home/tkloczko/rpmbuild/BUILD/sphinx-panels-0.6.0/sphinx_panels/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 177, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 37, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 128, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 346, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```

### Steps to reproduce

1. run `python setup.py build_sphinx -b man`

### The version of Python you're using

3.8.12

### Your operating system

Linux/x86_64

**Comment by kloczek** [comment]
gentle ping 😄

**Comment by Apteryks** [comment]
I had to comment out this extension to build the `info` documentation of the Matplotlib project.

**Comment by chrisjsewell** [comment]
See #67

**Comment by kloczek** [comment]
gentle ping .. 😃

**Comment by kloczek** [comment]
Closing as I see that new 0.18.0 no longer is using `sphinx-panels`.
Thank you 👍

**Comment by kloczek** [comment]
Second thought.
I'm not about choose instead `sphinx-design` https://github.com/executablebooks/sphinx-design/issues/54.
